title: Seaquence
description: Seaquence App
copyright: Okaynokay

permalink: /blog/:year-:month-:day-:title

plugins: [jekyll-paginate]
paginate_path: "/blog/page:num/"
paginate: 5
markdown: kramdown

offsiteimgs: http://media.quilime.com/seaqblerg/media
blogimgs: images/blog

app:
  price: $6.99 USD
  storeurl: https://itunes.apple.com/us/app/seaquence/id1106270489