title: Seaquence
description: Seaquence App
copyright: Okaynokay

permalink: /blog/:year-:month-:day-:title

gems: [jekyll-paginate]
paginate_path: "/blog/page:num/"
paginate: 5

offsiteimgs: http://media.quilime.com/seaqblerg/media
blogimgs: images/blog

app:
  price: $9.99
  sale: $6.99
